ng: "~/windata/ng"
mnt: "/ng"
imports: "path/to/imports"
sab: "http://sabnzbd.home/sabnzbd/api?apikey=SECRET"
pvrs:
  radarr:
    type: Radarr
    url: "http://radarr.home/api?apikey=SECRET"
  radarrfr:
    type: Radarr
    url: "http://radarrfr.home/api?apikey=SECRET"
  sonarr:
    type: Sonarr
    url: "http://sonarr.home/api?apikey=SECRET"
